language: node_js
node_js:
- '11'
cache: npm
addons:
  ssh_known_hosts:
  - "$REMOTE_HOST"
  - "$REMOTE_HOST_IP"
notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
after_success:
- chmod +x ".travis/public-patch.js"
- chmod +x ".travis/public-deploy.sh"
- node .travis/public-patch.js
- ".travis/public-deploy.sh"
before_install:
- openssl aes-256-cbc -K $encrypted_26b0030bdaba_key -iv $encrypted_26b0030bdaba_iv
  -in .travis/deploy.key.enc -out .travis/deploy.key -d
